# Generated by Django 4.2.4 on 2023-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourbusiness', models.CharField(max_length=300)),
                ('yourname', models.CharField(max_length=300)),
                ('mobilenumber', models.IntegerField()),
                ('emailaddress', models.EmailField(max_length=254)),
                ('business', models.CharField(max_length=200)),
            ],
        ),
    ]
